# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1650158859f162a72a869a75ac3cf86183b6403912fea877b226dbf649ed470d4cb148bf449eea50007fdc20ab0b2d4c01057964e06cb2be90b8169fcc965eae

test:
  secret_key_base: c77709ba98e3e0e8173f5ffd1f3bcd357fa6fbafdef3266ff48be12be14e5010f62c32e94cb29855ca60da81e6a335a840ceaa1f5c34dff0207e18ce5aa8a292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
